### ISSUE TITLE
so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by li-source** [ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch#3]
when i run python main.py --dataset vmrdcompv1 --frame all_in_one --net res101 --cuda

Traceback (most recent call last):
  File "/home/litong/vmrd-pytorch1.0/main.py", line 22, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/litong/vmrd-pytorch1.0/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/litong/vmrd-pytorch1.0/datasets/factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "/home/litong/vmrd-pytorch1.0/datasets/pascal_voc.py", line 23, in <module>
    from .imdb import imdb
  File "/home/litong/vmrd-pytorch1.0/datasets/imdb.py", line 14, in <module>
    from model.utils.cython_bbox import bbox_overlaps
ImportError: /home/litong/vmrd-pytorch1.0/model/utils/cython_bbox.so: undefined symbol: _Py_ZeroStruct

**Comment by le-wei** [comment]
@li-source 
I think your python environment is inconsistent with the python that generated the so file, you should regenerate one yourself. git clone `https://github.com/jwyang/faster-rcnn.pytorch` .Modify the make.sh file in the lib folder to change python to the python you want to use. Then execute make.sh to generate the so file

**Comment by li-source** [comment]
OK，thanks. Otherwise what is your  python environment?Mine is python3.6.2

**Comment by le-wei** [comment]
Hi,My python environment python3.7.But ,I think this code will work well in the python2 environment

**Comment by li-source** [comment]
> Hi,My python environment python3.7.But ,I think this code will work well in the python2 environment

For pytorch1.0 version，is python2 also available?

**Comment by le-wei** [comment]
Sorry, I mean python2.x environment

**Comment by li-source** [comment]
ok，thanks. I will try.

**Comment by xjtAlgo** [comment]
Hello, have you run through successfully the program in python2.x environment currently?

**Comment by ZhangHanbo** [comment]
> when i run python main.py --dataset vmrdcompv1 --frame all_in_one --net res101 --cuda
> 
> Traceback (most recent call last):
> File "/home/litong/vmrd-pytorch1.0/main.py", line 22, in
> from roi_data_layer.roidb import combined_roidb
> File "/home/litong/vmrd-pytorch1.0/roi_data_layer/roidb.py", line 9, in
> from datasets.factory import get_imdb
> File "/home/litong/vmrd-pytorch1.0/datasets/factory.py", line 14, in
> from datasets.pascal_voc import pascal_voc
> File "/home/litong/vmrd-pytorch1.0/datasets/pascal_voc.py", line 23, in
> from .imdb import imdb
> File "/home/litong/vmrd-pytorch1.0/datasets/imdb.py", line 14, in
> from model.utils.cython_bbox import bbox_overlaps
> ImportError: /home/litong/vmrd-pytorch1.0/model/utils/cython_bbox.so: undefined symbol: _Py_ZeroStruct

Sorry for the delay.

You should first follow https://github.com/jwyang/faster-rcnn.pytorch to make faster RCNN work. 

It would be better to use the master branch and PyTorch 0.4.1. Note that 0.4.0 and 1.x will not work for the master branch.

**Comment by ZhangHanbo** [comment]
> Hello, have you run through successfully the program in python2.x environment currently?

Sorry for the delay.

You should first follow https://github.com/jwyang/faster-rcnn.pytorch to make faster RCNN work.

It would be better to use the master branch and PyTorch 0.4.1. Note that 0.4.0 and 1.x will not work for the master branch.
