### ISSUE TITLE
ImportError: No module named ops

### ISSUE THREAD

**Issue by li-source** [ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch#4]
when i run python main.py --dataset vmrdcompv1 --frame mgn --net res101 --cuda

Traceback (most recent call last):
  File "/home/litong/Visual-Manipulation-Relationship-Network-Pytorch-pytorch1.0/main.py", line 25, in <module>
    from model.utils.net_utils import weights_normal_init, save_net, load_net, \
  File "/home/litong/Visual-Manipulation-Relationship-Network-Pytorch-pytorch1.0/model/utils/net_utils.py", line 11, in <module>
    from model.roi_layers import nms
  File "/home/litong/Visual-Manipulation-Relationship-Network-Pytorch-pytorch1.0/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/litong/Visual-Manipulation-Relationship-Network-Pytorch-pytorch1.0/model/roi_layers/nms.py", line 3, in <module>
    from torchvision.ops import nms
ImportError: No module named ops

**Comment by ZhangHanbo** [comment]
> when i run python main.py --dataset vmrdcompv1 --frame mgn --net res101 --cuda
> 
> Traceback (most recent call last):
> File "/home/litong/Visual-Manipulation-Relationship-Network-Pytorch-pytorch1.0/main.py", line 25, in
> from model.utils.net_utils import weights_normal_init, save_net, load_net,
> File "/home/litong/Visual-Manipulation-Relationship-Network-Pytorch-pytorch1.0/model/utils/net_utils.py", line 11, in
> from model.roi_layers import nms
> File "/home/litong/Visual-Manipulation-Relationship-Network-Pytorch-pytorch1.0/model/roi_layers/**init**.py", line 3, in
> from .nms import nms
> File "/home/litong/Visual-Manipulation-Relationship-Network-Pytorch-pytorch1.0/model/roi_layers/nms.py", line 3, in
> from torchvision.ops import nms
> ImportError: No module named ops

If you use the pytorch1.0 branch, you should make sure that the torch version >= 1.4.0.
