### ISSUE TITLE
ModuleNotFoundError: No module named 'model.utils.cython_bbox'

### ISSUE THREAD

**Issue by BHWWS** [ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch#9]
when I run python main.py --dataset vmrdcompv1 --frame mgn --net res101 --cuda directly, I meet the following error:

Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/content/drive/MyDrive/VMRN-Pytorch/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/content/drive/MyDrive/VMRN-Pytorch/datasets/factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "/content/drive/MyDrive/VMRN-Pytorch/datasets/pascal_voc.py", line 23, in <module>
    from .imdb import imdb
  File "/content/drive/MyDrive/VMRN-Pytorch/datasets/imdb.py", line 19, in <module>
    from model.utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'model.utils.cython_bbox'

In model.util file, I do not find the cython_bbox file, so how can I fix this problem?

**Comment by dmsgithub12** [comment]
Hello, I have a similar problem. Have you solved it?

**Comment by Wf199812** [comment]
I have a similar problem，too. Have you solved it?

**Comment by Chris310826** [comment]
I have a similar problem，too. Have you solved it?

**Comment by ZhangHanbo** [comment]
try build the cython module, and import them properly
